"use client";

import { FormEvent, useState } from "react";
import { Bot, Send, X } from "lucide-react";

type ChatMessage = { role: "user" | "assistant"; content: string };
export function AiChat({ onClose }: { onClose: () => void }) {
  const [messages, setMessages] = useState<ChatMessage[]>([{ role: "assistant", content: "你好，我可以帮你查找物品位置、库存数量、临期物品和待采购清单。" }]);
  const [input, setInput] = useState(""); const [loading, setLoading] = useState(false);
  const ask = async (event: FormEvent) => { event.preventDefault(); const question = input.trim(); if (!question || loading) return; const next = [...messages, { role: "user" as const, content: question }]; setMessages(next); setInput(""); setLoading(true); try { const response = await fetch("/api/ai/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next }) }); const result = await response.json(); setMessages((current) => [...current, { role: "assistant", content: response.ok ? result.answer : result.error || "AI 暂时无法回答" }]); } catch { setMessages((current) => [...current, { role: "assistant", content: "网络连接失败，请稍后重试。" }]); } finally { setLoading(false); } };
  return <div className="fixed bottom-4 right-4 z-[100] flex h-[min(680px,calc(100vh-32px))] w-[min(420px,calc(100vw-32px))] flex-col overflow-hidden rounded-3xl border shadow-2xl" style={{ background: "var(--surface-solid)", borderColor: "var(--border)" }}><header className="flex items-center gap-3 border-b p-4" style={{ borderColor: "var(--border)" }}><div className="grid size-10 place-items-center rounded-2xl" style={{ background: "var(--primary-soft)", color: "var(--primary)" }}><Bot size={20} /></div><div className="min-w-0 flex-1"><h2 className="m-0 text-base font-black">库存 AI 助手</h2><p className="mb-0 mt-1 text-xs muted">问问物品在哪里、还有多少</p></div><button onClick={onClose} className="btn-ghost grid size-8 place-items-center p-0" aria-label="关闭 AI 助手"><X size={17} /></button></header><div className="min-h-0 flex-1 space-y-3 overflow-y-auto p-4">{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`flex ${message.role === "user" ? "justify-end" : "justify-start"}`}><div className={`max-w-[88%] whitespace-pre-wrap rounded-2xl px-3 py-2.5 text-sm leading-6 ${message.role === "user" ? "text-white" : ""}`} style={message.role === "user" ? { background: "var(--primary)" } : { background: "var(--surface-soft)" }}>{message.content}</div></div>)}{loading && <div className="text-xs muted">AI 正在查找库存…</div>}</div><form onSubmit={ask} className="flex gap-2 border-t p-3" style={{ borderColor: "var(--border)" }}><input className="input min-w-0 flex-1" value={input} onChange={(event) => setInput(event.target.value)} placeholder="例如：洗衣液在哪里？" /><button className="btn-primary grid size-11 shrink-0 place-items-center p-0" aria-label="发送问题"><Send size={17} /></button></form></div>;
}
