"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useEffect, useState } from "react";
import { Download, Upload, Users, UserPlus, History } from "lucide-react";

export function DataTools({ onToast }: { onToast: (message: string) => void }) {
  const [members, setMembers] = useState<{ id: string; name: string; color: string }[]>([]);
  const [name, setName] = useState("");
  const [activity, setActivity] = useState<{ id: string; action: string; itemName: string | null; createdAt: string }[]>([]);
  const load = () => { fetch("/api/members").then((r) => r.json()).then(setMembers).catch(() => undefined); fetch("/api/activity").then((r) => r.json()).then(setActivity).catch(() => undefined); };
  useEffect(load, []);
  const addMember = async () => { if (!name.trim()) return; const response = await fetch("/api/members", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); if (response.ok) { setName(""); load(); onToast("成员已添加"); } };
  const importFile = async (file?: File) => { if (!file) return; try { const rows = JSON.parse(await file.text()); const response = await fetch("/api/items/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(rows) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); onToast(`已导入 ${result.count} 件物品`); } catch (error) { onToast(error instanceof Error ? error.message : "导入失败"); } };
  return <details className="surface group rounded-3xl p-5"><summary className="flex cursor-pointer list-none items-center gap-3 [&::-webkit-details-marker]:hidden"><div className="grid size-11 place-items-center rounded-2xl" style={{ background: "var(--primary-soft)", color: "var(--primary)" }}><Download size={20} /></div><div className="min-w-0 flex-1"><h3 className="m-0 text-sm font-black">数据安全与家庭成员</h3><p className="mb-0 mt-1 text-xs muted">备份、恢复、操作记录与成员标记</p></div></summary><div className="mt-5 space-y-4 border-t pt-4" style={{ borderColor: "var(--border)" }}><div className="flex flex-wrap gap-2"><a className="btn-primary flex items-center gap-2 text-xs" href="/api/backup"><Download size={14} />导出完整备份</a><a className="btn-ghost flex items-center gap-2 text-xs" href="/api/items?export=1"><Download size={14} />导出物品 JSON</a><label className="btn-ghost flex cursor-pointer items-center gap-2 text-xs"><Upload size={14} />导入 JSON<input type="file" accept="application/json,.json" className="hidden" onChange={(e) => importFile(e.target.files?.[0])} /></label></div><div><div className="mb-2 flex items-center gap-2 text-xs font-bold muted"><Users size={14} />家庭成员</div><div className="flex flex-wrap gap-2">{members.map((member) => <span key={member.id} className="rounded-xl px-2.5 py-1.5 text-xs font-bold" style={{ background: "var(--surface-soft)", color: member.color }}>{member.name}</span>)}<div className="flex gap-2"><input className="input h-8 w-28 text-xs" value={name} onChange={(e) => setName(e.target.value)} placeholder="成员名称" /><button onClick={addMember} className="btn-ghost grid size-8 place-items-center p-0"><UserPlus size={14} /></button></div></div></div><div><div className="mb-2 flex items-center gap-2 text-xs font-bold muted"><History size={14} />最近操作</div>{activity.slice(0, 5).map((entry) => <div key={entry.id} className="flex justify-between gap-3 py-1 text-xs muted"><span>{entry.action} · {entry.itemName || "物品"}</span><span>{new Date(entry.createdAt).toLocaleDateString("zh-CN")}</span></div>)}</div></div></details>;
}
